### ISSUE TITLE
is xslt 2.0 supported?

### ISSUE THREAD

**Issue by bjuergens** [murrayju/xslt#11]
Is XSLT 2.0 support right now? 
is support for xslt 2.0 planned?

**Comment by murrayju** [comment]
Should work fine, in so much as the underlying browser supports it. This project is just a wrapper around the different browser implementations. I've done little testing with 2.0 since 1.0 is more widely supported. @wotanii if you try out 2.0 and do find some problems, make issues here and I'll be happy to look into them.
